database: postgres
spring:  
  thymeleaf:
    mode: HTML
  h2:
    console:
      enabled: false
  jpa:  
    hibernate:  
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true  
  datasource:  
    url: "jdbc:postgresql://ec2-99-80-200-225.eu-west-1.compute.amazonaws.com:5432/d15ccopo42lqjv"  
    username: pcaazqsilzfoak  
    password: be095ae58bfeda2bccde2b683f9ad7b1143c646dbbf2c4c5f83f8dd2d28c520d
    sqlScriptEncoding: UTF-8
    type: org.apache.tomcat.jdbc.pool.DataSource
stripe:
  key:
    public: pk_test_51IeGm1A32JKQZm0zQ9rDl6vL1KuiQYaGHiszd0nJ4dUDy5AW3K9tmHjJLdbdxbsPivHTtQ5JR7uvNlo1tAP1Of6v00oarGizZJ
    secret: sk_test_51IeGm1A32JKQZm0ztexmoajNRqjPuSxawtIfVhuBY2iu6AcCFAd1ilkWRSg6rUNFyTZ2TPcJSQATc8aC8gep7FW600iew5bfrA
